include:
  - project: "cocainefarm/templates/ci"
    file: "s3.yaml"

variables:
  S3_SRC: dist

build:
  image: ejectedspace/pandoc-builder
  stage: build
  script:
    - make build
  artifacts:
    paths:
      - dist
  only:
    refs:
      - master
